version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: monthly
      time: "06:30"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "- (php) "
    target-branch: main
    open-pull-requests-limit: 1